// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9B7HIHaVp3KZ3zRboSZMHF3iOo3su2Jc',
    appId: '1:624508724825:web:651a4908cf12c5d125b348',
    messagingSenderId: '624508724825',
    projectId: 'valueproai',
    authDomain: 'valueproai.firebaseapp.com',
    storageBucket: 'valueproai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQhBsfm5ICEbdvLEsdifYbiidyckSQNk',
    appId: '1:624508724825:android:1b2eb782875b4deb25b348',
    messagingSenderId: '624508724825',
    projectId: 'valueproai',
    storageBucket: 'valueproai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALsYPlnknYisVVnvgJh8QqFFicix1O_Lg',
    appId: '1:624508724825:ios:9afbde9cba92043925b348',
    messagingSenderId: '624508724825',
    projectId: 'valueproai',
    storageBucket: 'valueproai.firebasestorage.app',
    iosBundleId: 'com.value.pro.valuepro',
  );
}
